# Use official Maven image to build
FROM maven:3.9.4-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean install -DskipTests

# Use lightweight Java runtime to run the app
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/language-Api-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
